// <auto-generated />
using System;
using ERPiData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ERPiData.Migrations
{
    [DbContext(typeof(ErpiDbContext))]
    [Migration("20260805081929_DodajPoljaKonta")]
    partial class DodajPoljaKonta
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("ERPiData.Models.Core.Firma", b =>
                {
                    b.Property<int>("FirmaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresa")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FunkcijaZastupnika")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JbkjsBroj")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaticniBroj")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Napomena")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PfrKasirName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PfrPacKod")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PfrSimulatorMod")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PfrUrl")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pib")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("PodracunPoslovneJedinice")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("PosebanRacun")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("PttIMesto")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SefApiKey")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("SefEnvironment")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sifra")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SifraDelatnosti")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("SifraOpstine")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Zastupnik")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("ZiroRacun")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("FirmaId");

                    b.HasIndex("Sifra")
                        .IsUnique();

                    b.ToTable("Firme");
                });

            modelBuilder.Entity("ERPiData.Models.Core.Konto", b =>
                {
                    b.Property<int>("KontoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrojKonta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSintetika")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Klasa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mesto")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NazivKonta")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("StariKonto")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ulica")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("VrstaKonta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ZiroRacun")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("KontoId");

                    b.HasIndex("BrojKonta")
                        .IsUnique();

                    b.ToTable("Konta");
                });

            modelBuilder.Entity("ERPiData.Models.Core.Korisnik", b =>
                {
                    b.Property<int>("KorisnikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImeIPrezime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KorisnickoIme")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LozinkaHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PoslednjaPrijava")
                        .HasColumnType("TEXT");

                    b.Property<int>("Uloga")
                        .HasColumnType("INTEGER");

                    b.HasKey("KorisnikId");

                    b.HasIndex("KorisnickoIme")
                        .IsUnique();

                    b.ToTable("Korisnici");

                    b.HasData(
                        new
                        {
                            KorisnikId = 1,
                            ImeIPrezime = "Administrator",
                            IsActive = true,
                            KorisnickoIme = "admin",
                            LozinkaHash = "PBKDF2$100000$CnYWiALqycqWTueq6ayEvQ==$hvm9e8z3e+KVeRsego3azOuoTp3q64deikPgUB9/D4o=",
                            Uloga = 0
                        });
                });

            modelBuilder.Entity("ERPiData.Models.Core.MestoTroska", b =>
                {
                    b.Property<int>("MestoTroskaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAktivno")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Napomena")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sifra")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Tip")
                        .HasColumnType("INTEGER");

                    b.HasKey("MestoTroskaId");

                    b.HasIndex("Sifra")
                        .IsUnique();

                    b.ToTable("MestaTroska");
                });

            modelBuilder.Entity("ERPiData.Models.Core.Partner", b =>
                {
                    b.Property<int>("PartnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresa")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("BankovniRacun")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("JeBanka")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("JeDobavljac")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("JeKupac")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("JePoreskaUprava")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("JeRadnik")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Jmbg")
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("KontoPartnera")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaticniBroj")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NazivBanke")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pib")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("PttIMesto")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SifraPartnera")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ZiroRacun")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("PartnerId");

                    b.HasIndex("SifraPartnera")
                        .IsUnique();

                    b.ToTable("Partneri");
                });

            modelBuilder.Entity("ERPiData.Models.Finansije.KamatnaStopa", b =>
                {
                    b.Property<int>("KamatnaStopaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatumOd")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GodisnjaStopaProcenat")
                        .HasColumnType("decimal(9, 4)");

                    b.Property<string>("Napomena")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("KamatnaStopaId");

                    b.ToTable("KamatneStope");
                });

            modelBuilder.Entity("ERPiData.Models.Finansije.Nalog", b =>
                {
                    b.Property<int>("NalogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrojNaloga")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DatumKnjizenja")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumNaloga")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IzvorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IzvorModula")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Opis")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UkupnoDuguje")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("UkupnoPotrazuje")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("VrstaNaloga")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("NalogId");

                    b.ToTable("Nalozi");
                });

            modelBuilder.Entity("ERPiData.Models.Finansije.PdvZapis", b =>
                {
                    b.Property<int>("PdvZapisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrojDokumenta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumDokumenta")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumPoreskogDogadjaja")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IznosPdv")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("NalogId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Napomena")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Osnovica")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("PartnerId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("StopaPdv")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("TipKnjige")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Ukupno")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("PdvZapisId");

                    b.HasIndex("NalogId");

                    b.HasIndex("PartnerId");

                    b.ToTable("PdvZapisi");
                });

            modelBuilder.Entity("ERPiData.Models.Finansije.PfrRacun", b =>
                {
                    b.Property<int>("PfrRacunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrojRacuna")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Iznos")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Napomena")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PartnerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PfrBroj")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("QrKodUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("TipRacuna")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("PfrRacunId");

                    b.HasIndex("PartnerId");

                    b.ToTable("PfrRacuni");
                });

            modelBuilder.Entity("ERPiData.Models.Finansije.SefDokument", b =>
                {
                    b.Property<int>("SefDokumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrojDokumenta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CirId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumDokumenta")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DatumSlanja")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IznosPdv")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Napomena")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Osnovica")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("PartnerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("TipDokumenta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("UblXmlContent")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Ukupno")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("SefDokumentId");

                    b.HasIndex("PartnerId");

                    b.ToTable("SefDokumenti");
                });

            modelBuilder.Entity("ERPiData.Models.Finansije.StavkaNaloga", b =>
                {
                    b.Property<int>("StavkaNalogaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrojDokumenta")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DatumDokumenta")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Duguje")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("KontoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("KursValute")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int?>("MestoTroskaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NalogId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Opis")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Osnovica")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("PartnerId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Potrazuje")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("RedniBroj")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("StopaPdv")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Valuta")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ValutaDospela")
                        .HasColumnType("TEXT");

                    b.HasKey("StavkaNalogaId");

                    b.HasIndex("KontoId");

                    b.HasIndex("MestoTroskaId");

                    b.HasIndex("NalogId");

                    b.HasIndex("PartnerId");

                    b.ToTable("StavkeNaloga");
                });

            modelBuilder.Entity("ERPiData.Models.Finansije.ZatvaranjeStavke", b =>
                {
                    b.Property<int>("ZatvaranjeStavkeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatumZatvaranja")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Iznos")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("KorisnikId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Napomena")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<int>("StavkaDugujeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StavkaPotrazujeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VrstaZatvaranja")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("ZatvaranjeStavkeId");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("StavkaDugujeId");

                    b.HasIndex("StavkaPotrazujeId");

                    b.ToTable("ZatvaranjaStavki");
                });

            modelBuilder.Entity("ERPiData.Models.Magacin.Artikal", b =>
                {
                    b.Property<int>("ArtikalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Barkod")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("JedinicaMere")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("KlasifikacionaSifra")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NabavnaCena")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pakovanje")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PdvStopa")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("ProdajnaCena")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("SifraArtikla")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TarifniBroj")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("ArtikalId");

                    b.HasIndex("SifraArtikla")
                        .IsUnique();

                    b.ToTable("Artikli");
                });

            modelBuilder.Entity("ERPiData.Models.Magacin.Kalkulacija", b =>
                {
                    b.Property<int>("KalkulacijaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrojFaktureDobavljaca")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("BrojKalkulacije")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DatumFakture")
                        .HasColumnType("TEXT");

                    b.Property<int>("MagacinId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Napomena")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PartnerId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UkupnoNabavna")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("UkupnoPdv")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("UkupnoProdajna")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("VrstaKalkulacije")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("KalkulacijaId");

                    b.HasIndex("MagacinId");

                    b.HasIndex("PartnerId");

                    b.ToTable("Kalkulacije");
                });

            modelBuilder.Entity("ERPiData.Models.Magacin.Magacin", b =>
                {
                    b.Property<int>("MagacinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NazivMagacina")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OdgovornoLice")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SifraMagacina")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("VrstaMagacina")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("MagacinId");

                    b.HasIndex("SifraMagacina")
                        .IsUnique();

                    b.ToTable("Magacini");
                });

            modelBuilder.Entity("ERPiData.Models.Magacin.StavkaKalkulacije", b =>
                {
                    b.Property<int>("StavkaKalkulacijeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArtikalId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("IznosNabavni")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("IznosPdv")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("IznosProdajni")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("KalkulacijaId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Kolicina")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("MarzaProcenat")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("NabavnaCena")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("PdvStopa")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("ProdajnaCena")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("RabatProcenat")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("StavkaKalkulacijeId");

                    b.HasIndex("ArtikalId");

                    b.HasIndex("KalkulacijaId");

                    b.ToTable("StavkeKalkulacije");
                });

            modelBuilder.Entity("ERPiData.Models.Finansije.PdvZapis", b =>
                {
                    b.HasOne("ERPiData.Models.Finansije.Nalog", "Nalog")
                        .WithMany()
                        .HasForeignKey("NalogId");

                    b.HasOne("ERPiData.Models.Core.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId");

                    b.Navigation("Nalog");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("ERPiData.Models.Finansije.PfrRacun", b =>
                {
                    b.HasOne("ERPiData.Models.Core.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("ERPiData.Models.Finansije.SefDokument", b =>
                {
                    b.HasOne("ERPiData.Models.Core.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("ERPiData.Models.Finansije.StavkaNaloga", b =>
                {
                    b.HasOne("ERPiData.Models.Core.Konto", "Konto")
                        .WithMany()
                        .HasForeignKey("KontoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERPiData.Models.Core.MestoTroska", "MestoTroska")
                        .WithMany()
                        .HasForeignKey("MestoTroskaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ERPiData.Models.Finansije.Nalog", "Nalog")
                        .WithMany("Stavke")
                        .HasForeignKey("NalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERPiData.Models.Core.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Konto");

                    b.Navigation("MestoTroska");

                    b.Navigation("Nalog");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("ERPiData.Models.Finansije.ZatvaranjeStavke", b =>
                {
                    b.HasOne("ERPiData.Models.Core.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ERPiData.Models.Finansije.StavkaNaloga", "StavkaDuguje")
                        .WithMany()
                        .HasForeignKey("StavkaDugujeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERPiData.Models.Finansije.StavkaNaloga", "StavkaPotrazuje")
                        .WithMany()
                        .HasForeignKey("StavkaPotrazujeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Korisnik");

                    b.Navigation("StavkaDuguje");

                    b.Navigation("StavkaPotrazuje");
                });

            modelBuilder.Entity("ERPiData.Models.Magacin.Kalkulacija", b =>
                {
                    b.HasOne("ERPiData.Models.Magacin.Magacin", "Magacin")
                        .WithMany()
                        .HasForeignKey("MagacinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERPiData.Models.Core.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Magacin");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("ERPiData.Models.Magacin.StavkaKalkulacije", b =>
                {
                    b.HasOne("ERPiData.Models.Magacin.Artikal", "Artikal")
                        .WithMany()
                        .HasForeignKey("ArtikalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERPiData.Models.Magacin.Kalkulacija", "Kalkulacija")
                        .WithMany("Stavke")
                        .HasForeignKey("KalkulacijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artikal");

                    b.Navigation("Kalkulacija");
                });

            modelBuilder.Entity("ERPiData.Models.Finansije.Nalog", b =>
                {
                    b.Navigation("Stavke");
                });

            modelBuilder.Entity("ERPiData.Models.Magacin.Kalkulacija", b =>
                {
                    b.Navigation("Stavke");
                });
#pragma warning restore 612, 618
        }
    }
}
