// <auto-generated />
using System;
using ERPiData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ERPiData.Migrations
{
    [DbContext(typeof(ErpiDbContext))]
    [Migration("20260805083002_DodajRobnoIMaterijalno")]
    partial class DodajRobnoIMaterijalno
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("ERPiData.Models.Core.Firma", b =>
                {
                    b.Property<int>("FirmaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresa")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FunkcijaZastupnika")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JbkjsBroj")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaticniBroj")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Napomena")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PfrKasirName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PfrPacKod")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PfrSimulatorMod")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PfrUrl")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pib")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("PodracunPoslovneJedinice")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("PosebanRacun")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("PttIMesto")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SefApiKey")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("SefEnvironment")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sifra")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SifraDelatnosti")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("SifraOpstine")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Zastupnik")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("ZiroRacun")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("FirmaId");

                    b.HasIndex("Sifra")
                        .IsUnique();

                    b.ToTable("Firme");
                });

            modelBuilder.Entity("ERPiData.Models.Core.Konto", b =>
                {
                    b.Property<int>("KontoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrojKonta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSintetika")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Klasa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mesto")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NazivKonta")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("StariKonto")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ulica")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("VrstaKonta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ZiroRacun")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("KontoId");

                    b.HasIndex("BrojKonta")
                        .IsUnique();

                    b.ToTable("Konta");
                });

            modelBuilder.Entity("ERPiData.Models.Core.Korisnik", b =>
                {
                    b.Property<int>("KorisnikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImeIPrezime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KorisnickoIme")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LozinkaHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PoslednjaPrijava")
                        .HasColumnType("TEXT");

                    b.Property<int>("Uloga")
                        .HasColumnType("INTEGER");

                    b.HasKey("KorisnikId");

                    b.HasIndex("KorisnickoIme")
                        .IsUnique();

                    b.ToTable("Korisnici");

                    b.HasData(
                        new
                        {
                            KorisnikId = 1,
                            ImeIPrezime = "Administrator",
                            IsActive = true,
                            KorisnickoIme = "admin",
                            LozinkaHash = "PBKDF2$100000$CnYWiALqycqWTueq6ayEvQ==$hvm9e8z3e+KVeRsego3azOuoTp3q64deikPgUB9/D4o=",
                            Uloga = 0
                        });
                });

            modelBuilder.Entity("ERPiData.Models.Core.MestoTroska", b =>
                {
                    b.Property<int>("MestoTroskaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAktivno")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Napomena")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sifra")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Tip")
                        .HasColumnType("INTEGER");

                    b.HasKey("MestoTroskaId");

                    b.HasIndex("Sifra")
                        .IsUnique();

                    b.ToTable("MestaTroska");
                });

            modelBuilder.Entity("ERPiData.Models.Core.Partner", b =>
                {
                    b.Property<int>("PartnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresa")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("BankovniRacun")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("JeBanka")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("JeDobavljac")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("JeKupac")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("JePoreskaUprava")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("JeRadnik")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Jmbg")
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("KontoPartnera")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaticniBroj")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NazivBanke")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pib")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("PttIMesto")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SifraPartnera")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ZiroRacun")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("PartnerId");

                    b.HasIndex("SifraPartnera")
                        .IsUnique();

                    b.ToTable("Partneri");
                });

            modelBuilder.Entity("ERPiData.Models.Finansije.BlagajnickiNalog", b =>
                {
                    b.Property<int>("BlagajnickiNalogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrojKontaProtu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BrojNaloga")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsKnjizeno")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Iznos")
                        .HasColumnType("TEXT");

                    b.Property<string>("Korisnik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("NalogId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Napomena")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Svrha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UplatilacIsplatilac")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VrstaBlagajne")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VrstaNaloga")
                        .HasColumnType("INTEGER");

                    b.HasKey("BlagajnickiNalogId");

                    b.ToTable("BlagajnickiNalozi");
                });

            modelBuilder.Entity("ERPiData.Models.Finansije.KamatnaStopa", b =>
                {
                    b.Property<int>("KamatnaStopaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatumOd")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GodisnjaStopaProcenat")
                        .HasColumnType("decimal(9, 4)");

                    b.Property<string>("Napomena")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("KamatnaStopaId");

                    b.ToTable("KamatneStope");
                });

            modelBuilder.Entity("ERPiData.Models.Finansije.Kompenzacija", b =>
                {
                    b.Property<int>("KompenzacijaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrojDokumenta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsKnjizeno")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KontoPartnera1")
                        .HasColumnType("TEXT");

                    b.Property<string>("KontoPartnera2")
                        .HasColumnType("TEXT");

                    b.Property<string>("KontoPartnera3")
                        .HasColumnType("TEXT");

                    b.Property<string>("Korisnik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("NalogId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Napomena")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NazivPartnera")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NazivPartnera2")
                        .HasColumnType("TEXT");

                    b.Property<string>("NazivPartnera3")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Partner2Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Partner3Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PartnerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UkupanIznosKompenzacije")
                        .HasColumnType("TEXT");

                    b.Property<int>("Vrsta")
                        .HasColumnType("INTEGER");

                    b.HasKey("KompenzacijaId");

                    b.ToTable("Kompenzacije");
                });

            modelBuilder.Entity("ERPiData.Models.Finansije.KompenzacijaStavka", b =>
                {
                    b.Property<int>("KompenzacijaStavkaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrojDokumenta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BrojKonta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumDokumenta")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IznosFakture")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IznosPreostalo")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IznosZaKompenzaciju")
                        .HasColumnType("TEXT");

                    b.Property<int>("KompenzacijaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartnerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RedniBroj")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StavkaNalogaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Strana")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("KompenzacijaStavkaId");

                    b.HasIndex("KompenzacijaId");

                    b.ToTable("KompenzacijeStavke");
                });

            modelBuilder.Entity("ERPiData.Models.Finansije.KursnaListaStavka", b =>
                {
                    b.Property<int>("KursnaListaStavkaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<int>("Jedinica")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("KupovniKurs")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("NazivValute")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProdavniKurs")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("SrednjiKurs")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("ValutaOznaka")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("ValutaSifra")
                        .HasColumnType("INTEGER");

                    b.HasKey("KursnaListaStavkaId");

                    b.ToTable("KursneListeStavke");
                });

            modelBuilder.Entity("ERPiData.Models.Finansije.Nalog", b =>
                {
                    b.Property<int>("NalogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrojNaloga")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DatumKnjizenja")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumNaloga")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IzvorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IzvorModula")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Opis")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UkupnoDuguje")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("UkupnoPotrazuje")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("VrstaNaloga")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("NalogId");

                    b.ToTable("Nalozi");
                });

            modelBuilder.Entity("ERPiData.Models.Finansije.NeoporeziviIznosDnevnice", b =>
                {
                    b.Property<int>("NeoporeziviIznosDnevniceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatumOd")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IznosZemljaRsd")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Napomena")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("NeoporeziviIznosDnevniceId");

                    b.ToTable("NeoporeziviIznosiDnevnice");
                });

            modelBuilder.Entity("ERPiData.Models.Finansije.PdvZapis", b =>
                {
                    b.Property<int>("PdvZapisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrojDokumenta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumDokumenta")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumPoreskogDogadjaja")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IznosPdv")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("NalogId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Napomena")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Osnovica")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("PartnerId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("StopaPdv")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("TipKnjige")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Ukupno")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("PdvZapisId");

                    b.HasIndex("NalogId");

                    b.HasIndex("PartnerId");

                    b.ToTable("PdvZapisi");
                });

            modelBuilder.Entity("ERPiData.Models.Finansije.PfrRacun", b =>
                {
                    b.Property<int>("PfrRacunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrojRacuna")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Iznos")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Napomena")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PartnerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PfrBroj")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("QrKodUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("TipRacuna")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("PfrRacunId");

                    b.HasIndex("PartnerId");

                    b.ToTable("PfrRacuni");
                });

            modelBuilder.Entity("ERPiData.Models.Finansije.PutniNalog", b =>
                {
                    b.Property<int>("PutniNalogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Akontacija")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BrojDnevnica")
                        .HasColumnType("TEXT");

                    b.Property<string>("BrojNaloga")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumPolaska")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumPovratka")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsKnjizeno")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("IznosDnevniceRsd")
                        .HasColumnType("TEXT");

                    b.Property<string>("Jmbg")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("Korisnik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("NalogId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Napomena")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OstaliTroskovi")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrevoznoSredstvo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RadnoMesto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Relacija")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SvrhaPutovanja")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TrajanjeSati")
                        .HasColumnType("REAL");

                    b.Property<decimal>("TroskoviGoriva")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TroskoviPrevoza")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TroskoviSmestaja")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UkupnoDnevnice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UkupnoZaIsplatu")
                        .HasColumnType("TEXT");

                    b.Property<int>("Vrsta")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ZaposleniIme")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PutniNalogId");

                    b.ToTable("PutniNalozi");
                });

            modelBuilder.Entity("ERPiData.Models.Finansije.PutniNalogTrosakStavka", b =>
                {
                    b.Property<int>("PutniNalogTrosakStavkaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrojRacuna")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumRacuna")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Iznos")
                        .HasColumnType("TEXT");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PutniNalogId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RedniBroj")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VrstaTroska")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PutniNalogTrosakStavkaId");

                    b.HasIndex("PutniNalogId");

                    b.ToTable("PutniNaloziTroskoviStavke");
                });

            modelBuilder.Entity("ERPiData.Models.Finansije.SefDokument", b =>
                {
                    b.Property<int>("SefDokumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrojDokumenta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CirId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumDokumenta")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DatumSlanja")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IznosPdv")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Napomena")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Osnovica")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("PartnerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("TipDokumenta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("UblXmlContent")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Ukupno")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("SefDokumentId");

                    b.HasIndex("PartnerId");

                    b.ToTable("SefDokumenti");
                });

            modelBuilder.Entity("ERPiData.Models.Finansije.StavkaNaloga", b =>
                {
                    b.Property<int>("StavkaNalogaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrojDokumenta")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DatumDokumenta")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DevizniDuguje")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("DevizniPotrazuje")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Duguje")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("KontoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("KursValute")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int?>("MestoTroskaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NalogId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Opis")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Osnovica")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("PartnerId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Potrazuje")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("RedniBroj")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("StopaPdv")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Valuta")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ValutaDospela")
                        .HasColumnType("TEXT");

                    b.HasKey("StavkaNalogaId");

                    b.HasIndex("KontoId");

                    b.HasIndex("MestoTroskaId");

                    b.HasIndex("NalogId");

                    b.HasIndex("PartnerId");

                    b.ToTable("StavkeNaloga");
                });

            modelBuilder.Entity("ERPiData.Models.Finansije.ZatvaranjeStavke", b =>
                {
                    b.Property<int>("ZatvaranjeStavkeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatumZatvaranja")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Iznos")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("KorisnikId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Napomena")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<int>("StavkaDugujeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StavkaPotrazujeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VrstaZatvaranja")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("ZatvaranjeStavkeId");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("StavkaDugujeId");

                    b.HasIndex("StavkaPotrazujeId");

                    b.ToTable("ZatvaranjaStavki");
                });

            modelBuilder.Entity("ERPiData.Models.Magacin.Artikal", b =>
                {
                    b.Property<int>("ArtikalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Barkod")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("JedinicaMere")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("KlasifikacionaSifra")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NabavnaCena")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pakovanje")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PdvStopa")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("ProdajnaCena")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("SifraArtikla")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TarifniBroj")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("ArtikalId");

                    b.HasIndex("SifraArtikla")
                        .IsUnique();

                    b.ToTable("Artikli");
                });

            modelBuilder.Entity("ERPiData.Models.Magacin.Kalkulacija", b =>
                {
                    b.Property<int>("KalkulacijaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrojFaktureDobavljaca")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("BrojKalkulacije")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DatumFakture")
                        .HasColumnType("TEXT");

                    b.Property<int>("MagacinId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Napomena")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PartnerId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UkupnoNabavna")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("UkupnoPdv")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("UkupnoProdajna")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("VrstaKalkulacije")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("KalkulacijaId");

                    b.HasIndex("MagacinId");

                    b.HasIndex("PartnerId");

                    b.ToTable("Kalkulacije");
                });

            modelBuilder.Entity("ERPiData.Models.Magacin.Magacin", b =>
                {
                    b.Property<int>("MagacinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NazivMagacina")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OdgovornoLice")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SifraMagacina")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("VrstaMagacina")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("MagacinId");

                    b.HasIndex("SifraMagacina")
                        .IsUnique();

                    b.ToTable("Magacini");
                });

            modelBuilder.Entity("ERPiData.Models.Magacin.MaloprodajnaKalkulacija", b =>
                {
                    b.Property<int>("MaloprodajnaKalkulacijaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrojKalkulacije")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrojOtpremnice")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("BrojRacuna")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DatumOtpremnice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DatumRacuna")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsKnjizen")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTrgovinskiKnjizen")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MarzaProcenat")
                        .HasColumnType("decimal(9, 4)");

                    b.Property<decimal>("NabavnaVrednost")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("NalogId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("OstaliTroskovi")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("PoreskaStopaProcenat")
                        .HasColumnType("decimal(9, 4)");

                    b.Property<decimal>("Porez")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ProdajnaVrednost")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("RabatIznos")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("RabatPri")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("Razlika")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("SifraDobavljaca")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SifraMagacinaDaje")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SifraMagacinaPrima")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("SifraProdavnice")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SvegaNabavno")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("SvegaTroskovi")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TransportniTroskovi")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TransportnoOsiguranje")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TroskoviUskladistenja")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("UtovarIstovar")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("MaloprodajnaKalkulacijaId");

                    b.HasIndex("NalogId");

                    b.ToTable("MaloprodajneKalkulacije");
                });

            modelBuilder.Entity("ERPiData.Models.Magacin.MaloprodajnaKalkulacijaStavka", b =>
                {
                    b.Property<int>("MaloprodajnaKalkulacijaStavkaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BrojRazduzenja")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsKnjizen")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTrgovinskiKnjizen")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Iznos")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Kolicina")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int>("MaloprodajnaKalkulacijaId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("NabavnaCena")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("NabavnaVrednost")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("PorezIznos")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("PorezProcenat")
                        .HasColumnType("decimal(9, 4)");

                    b.Property<decimal>("PorezZaUplatu")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("PosebanPorezIznos")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("PosebanPorezProcenat")
                        .HasColumnType("decimal(9, 4)");

                    b.Property<decimal>("PrenetiPorez")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("PrenetiPosebanPorez")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ProdajnaCena")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("ProdajnaVrednost")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ProdajnaVrednostBezPoreza")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("RazlikaIznos")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("RazlikaProcenat")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<int>("RedniBroj")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SifraArtikla")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Taksa")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TarifniBroj")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Troskovi")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("MaloprodajnaKalkulacijaStavkaId");

                    b.HasIndex("MaloprodajnaKalkulacijaId");

                    b.ToTable("MaloprodajneKalkulacijeStavke");
                });

            modelBuilder.Entity("ERPiData.Models.Magacin.Materijal", b =>
                {
                    b.Property<int>("MaterijalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("JedinicaMere")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pakovanje")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SifraArtikla")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("MaterijalId");

                    b.ToTable("Materijali");
                });

            modelBuilder.Entity("ERPiData.Models.Magacin.MaterijalnaKartica", b =>
                {
                    b.Property<int>("MaterijalnaKarticaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cena")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("CenaIzlaz")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<DateTime>("DatumPromene")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Duguje")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Izlaz")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("OpisPromene")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Potrazuje")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("RedniBroj")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("SifraArtikla")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SifraMagacina")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Stanje")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Ulaz")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("MaterijalnaKarticaId");

                    b.ToTable("MaterijalneKartice");
                });

            modelBuilder.Entity("ERPiData.Models.Magacin.NivelacijaCena", b =>
                {
                    b.Property<int>("NivelacijaCenaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrojNivelacije")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatumNivelacije")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsKnjizen")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MagacinId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NalogId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Opis")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UkupnoRazlika")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("NivelacijaCenaId");

                    b.HasIndex("MagacinId");

                    b.HasIndex("NalogId");

                    b.ToTable("NivelacijeCena");
                });

            modelBuilder.Entity("ERPiData.Models.Magacin.NivelacijaStavka", b =>
                {
                    b.Property<int>("NivelacijaStavkaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ArtikalId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("KolicinaZaliha")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<int>("NivelacijaCenaId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("NovaCena")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("RazlikaPoJedinici")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("RedniBroj")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("StaraCena")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("UkupnaRazlika")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("NivelacijaStavkaId");

                    b.HasIndex("ArtikalId");

                    b.HasIndex("NivelacijaCenaId");

                    b.ToTable("NivelacijeStavke");
                });

            modelBuilder.Entity("ERPiData.Models.Magacin.PrimopredajaNalog", b =>
                {
                    b.Property<int>("PrimopredajaNalogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrojNaloga")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsKnjizen")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NalogId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SifraMagacinaDaje")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SifraMagacinaPrima")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StopaPdv")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("VrstaDokumenta")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("PrimopredajaNalogId");

                    b.HasIndex("NalogId");

                    b.ToTable("PrimopredajaNalozi");
                });

            modelBuilder.Entity("ERPiData.Models.Magacin.PrimopredajaStavka", b =>
                {
                    b.Property<int>("PrimopredajaStavkaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cena")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("Iznos")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Kolicina")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("PrimopredajaNalogId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RedniBroj")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SifraArtikla")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("PrimopredajaStavkaId");

                    b.HasIndex("PrimopredajaNalogId");

                    b.ToTable("PrimopredajaStavke");
                });

            modelBuilder.Entity("ERPiData.Models.Magacin.StavkaKalkulacije", b =>
                {
                    b.Property<int>("StavkaKalkulacijeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArtikalId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("IznosNabavni")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("IznosPdv")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("IznosProdajni")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("KalkulacijaId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Kolicina")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("MarzaProcenat")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("NabavnaCena")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("PdvStopa")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("ProdajnaCena")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("RabatProcenat")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("StavkaKalkulacijeId");

                    b.HasIndex("ArtikalId");

                    b.HasIndex("KalkulacijaId");

                    b.ToTable("StavkeKalkulacije");
                });

            modelBuilder.Entity("ERPiData.Models.Magacin.TrebovanjeNalog", b =>
                {
                    b.Property<int>("TrebovanjeNalogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrojNaloga")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsKnjizen")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SifraMagacina")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("TrebovanjeNalogId");

                    b.ToTable("TrebovanjeNalozi");
                });

            modelBuilder.Entity("ERPiData.Models.Magacin.TrebovanjeStavka", b =>
                {
                    b.Property<int>("TrebovanjeStavkaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cena")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("Iznos")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Kolicina")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("KontoTroska")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("RedniBroj")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SifraArtikla")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("TrebovanjeNalogId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TrebovanjeStavkaId");

                    b.HasIndex("TrebovanjeNalogId");

                    b.ToTable("TrebovanjeStavke");
                });

            modelBuilder.Entity("ERPiData.Models.Magacin.UlazNalog", b =>
                {
                    b.Property<int>("UlazNalogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrojNaloga")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrojRacuna")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DatumRacuna")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsKnjizen")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SifraMagacina")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("UlazNalogId");

                    b.ToTable("UlazNalozi");
                });

            modelBuilder.Entity("ERPiData.Models.Magacin.UlazStavka", b =>
                {
                    b.Property<int>("UlazStavkaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cena")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("Iznos")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Kolicina")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("RedniBroj")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SifraArtikla")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("UlazNalogId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UlazStavkaId");

                    b.HasIndex("UlazNalogId");

                    b.ToTable("UlazStavke");
                });

            modelBuilder.Entity("ERPiData.Models.Magacin.UvoznaKalkulacija", b =>
                {
                    b.Property<int>("UvoznaKalkulacijaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrojKalkulacije")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CarinaRsd")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("DatumInoFakture")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumKalkulacije")
                        .HasColumnType("TEXT");

                    b.Property<string>("InoBrojFakture")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("InoPartnerId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsKnjizen")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("KursValute")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int>("MagacinId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NalogId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("OstaliZavisniTroskoviRsd")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("PrevozRsd")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("SpedicijaRsd")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("UkupnaNabavnaVrednostRsd")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("UkupnoDevize")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("UkupnoFakturaRsd")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Valuta")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("UvoznaKalkulacijaId");

                    b.HasIndex("InoPartnerId");

                    b.HasIndex("MagacinId");

                    b.HasIndex("NalogId");

                    b.ToTable("UvozneKalkulacije");
                });

            modelBuilder.Entity("ERPiData.Models.Magacin.UvoznaStavka", b =>
                {
                    b.Property<int>("UvoznaStavkaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArtikalId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CarinaIznosRsd")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("CarinaProcenat")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("InoCenaDevize")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("InoIznosDevize")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("InoIznosRsd")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Kolicina")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("NabavnaCenaPoJediniciRsd")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("RasporedjeniZavisniTroskoviRsd")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("UkupnaNabavnaVrednostRsd")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("UvoznaKalkulacijaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UvoznaStavkaId");

                    b.HasIndex("ArtikalId");

                    b.HasIndex("UvoznaKalkulacijaId");

                    b.ToTable("UvozneStavke");
                });

            modelBuilder.Entity("ERPiData.Models.Finansije.KompenzacijaStavka", b =>
                {
                    b.HasOne("ERPiData.Models.Finansije.Kompenzacija", "Kompenzacija")
                        .WithMany("Stavke")
                        .HasForeignKey("KompenzacijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kompenzacija");
                });

            modelBuilder.Entity("ERPiData.Models.Finansije.PdvZapis", b =>
                {
                    b.HasOne("ERPiData.Models.Finansije.Nalog", "Nalog")
                        .WithMany()
                        .HasForeignKey("NalogId");

                    b.HasOne("ERPiData.Models.Core.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId");

                    b.Navigation("Nalog");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("ERPiData.Models.Finansije.PfrRacun", b =>
                {
                    b.HasOne("ERPiData.Models.Core.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("ERPiData.Models.Finansije.PutniNalogTrosakStavka", b =>
                {
                    b.HasOne("ERPiData.Models.Finansije.PutniNalog", "PutniNalog")
                        .WithMany("StavkeTroskova")
                        .HasForeignKey("PutniNalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PutniNalog");
                });

            modelBuilder.Entity("ERPiData.Models.Finansije.SefDokument", b =>
                {
                    b.HasOne("ERPiData.Models.Core.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("ERPiData.Models.Finansije.StavkaNaloga", b =>
                {
                    b.HasOne("ERPiData.Models.Core.Konto", "Konto")
                        .WithMany()
                        .HasForeignKey("KontoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERPiData.Models.Core.MestoTroska", "MestoTroska")
                        .WithMany()
                        .HasForeignKey("MestoTroskaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ERPiData.Models.Finansije.Nalog", "Nalog")
                        .WithMany("Stavke")
                        .HasForeignKey("NalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERPiData.Models.Core.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Konto");

                    b.Navigation("MestoTroska");

                    b.Navigation("Nalog");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("ERPiData.Models.Finansije.ZatvaranjeStavke", b =>
                {
                    b.HasOne("ERPiData.Models.Core.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ERPiData.Models.Finansije.StavkaNaloga", "StavkaDuguje")
                        .WithMany()
                        .HasForeignKey("StavkaDugujeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERPiData.Models.Finansije.StavkaNaloga", "StavkaPotrazuje")
                        .WithMany()
                        .HasForeignKey("StavkaPotrazujeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Korisnik");

                    b.Navigation("StavkaDuguje");

                    b.Navigation("StavkaPotrazuje");
                });

            modelBuilder.Entity("ERPiData.Models.Magacin.Kalkulacija", b =>
                {
                    b.HasOne("ERPiData.Models.Magacin.Magacin", "Magacin")
                        .WithMany()
                        .HasForeignKey("MagacinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERPiData.Models.Core.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Magacin");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("ERPiData.Models.Magacin.MaloprodajnaKalkulacija", b =>
                {
                    b.HasOne("ERPiData.Models.Finansije.Nalog", "Nalog")
                        .WithMany()
                        .HasForeignKey("NalogId");

                    b.Navigation("Nalog");
                });

            modelBuilder.Entity("ERPiData.Models.Magacin.MaloprodajnaKalkulacijaStavka", b =>
                {
                    b.HasOne("ERPiData.Models.Magacin.MaloprodajnaKalkulacija", "MaloprodajnaKalkulacija")
                        .WithMany("Stavke")
                        .HasForeignKey("MaloprodajnaKalkulacijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaloprodajnaKalkulacija");
                });

            modelBuilder.Entity("ERPiData.Models.Magacin.NivelacijaCena", b =>
                {
                    b.HasOne("ERPiData.Models.Magacin.Magacin", "Magacin")
                        .WithMany()
                        .HasForeignKey("MagacinId");

                    b.HasOne("ERPiData.Models.Finansije.Nalog", "Nalog")
                        .WithMany()
                        .HasForeignKey("NalogId");

                    b.Navigation("Magacin");

                    b.Navigation("Nalog");
                });

            modelBuilder.Entity("ERPiData.Models.Magacin.NivelacijaStavka", b =>
                {
                    b.HasOne("ERPiData.Models.Magacin.Artikal", "Artikal")
                        .WithMany()
                        .HasForeignKey("ArtikalId");

                    b.HasOne("ERPiData.Models.Magacin.NivelacijaCena", "NivelacijaCena")
                        .WithMany("Stavke")
                        .HasForeignKey("NivelacijaCenaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artikal");

                    b.Navigation("NivelacijaCena");
                });

            modelBuilder.Entity("ERPiData.Models.Magacin.PrimopredajaNalog", b =>
                {
                    b.HasOne("ERPiData.Models.Finansije.Nalog", "Nalog")
                        .WithMany()
                        .HasForeignKey("NalogId");

                    b.Navigation("Nalog");
                });

            modelBuilder.Entity("ERPiData.Models.Magacin.PrimopredajaStavka", b =>
                {
                    b.HasOne("ERPiData.Models.Magacin.PrimopredajaNalog", "PrimopredajaNalog")
                        .WithMany("Stavke")
                        .HasForeignKey("PrimopredajaNalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrimopredajaNalog");
                });

            modelBuilder.Entity("ERPiData.Models.Magacin.StavkaKalkulacije", b =>
                {
                    b.HasOne("ERPiData.Models.Magacin.Artikal", "Artikal")
                        .WithMany()
                        .HasForeignKey("ArtikalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERPiData.Models.Magacin.Kalkulacija", "Kalkulacija")
                        .WithMany("Stavke")
                        .HasForeignKey("KalkulacijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artikal");

                    b.Navigation("Kalkulacija");
                });

            modelBuilder.Entity("ERPiData.Models.Magacin.TrebovanjeStavka", b =>
                {
                    b.HasOne("ERPiData.Models.Magacin.TrebovanjeNalog", "TrebovanjeNalog")
                        .WithMany("Stavke")
                        .HasForeignKey("TrebovanjeNalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrebovanjeNalog");
                });

            modelBuilder.Entity("ERPiData.Models.Magacin.UlazStavka", b =>
                {
                    b.HasOne("ERPiData.Models.Magacin.UlazNalog", "UlazNalog")
                        .WithMany("Stavke")
                        .HasForeignKey("UlazNalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UlazNalog");
                });

            modelBuilder.Entity("ERPiData.Models.Magacin.UvoznaKalkulacija", b =>
                {
                    b.HasOne("ERPiData.Models.Core.Partner", "InoPartner")
                        .WithMany()
                        .HasForeignKey("InoPartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERPiData.Models.Magacin.Magacin", "Magacin")
                        .WithMany()
                        .HasForeignKey("MagacinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERPiData.Models.Finansije.Nalog", "Nalog")
                        .WithMany()
                        .HasForeignKey("NalogId");

                    b.Navigation("InoPartner");

                    b.Navigation("Magacin");

                    b.Navigation("Nalog");
                });

            modelBuilder.Entity("ERPiData.Models.Magacin.UvoznaStavka", b =>
                {
                    b.HasOne("ERPiData.Models.Magacin.Artikal", "Artikal")
                        .WithMany()
                        .HasForeignKey("ArtikalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERPiData.Models.Magacin.UvoznaKalkulacija", "UvoznaKalkulacija")
                        .WithMany("Stavke")
                        .HasForeignKey("UvoznaKalkulacijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artikal");

                    b.Navigation("UvoznaKalkulacija");
                });

            modelBuilder.Entity("ERPiData.Models.Finansije.Kompenzacija", b =>
                {
                    b.Navigation("Stavke");
                });

            modelBuilder.Entity("ERPiData.Models.Finansije.Nalog", b =>
                {
                    b.Navigation("Stavke");
                });

            modelBuilder.Entity("ERPiData.Models.Finansije.PutniNalog", b =>
                {
                    b.Navigation("StavkeTroskova");
                });

            modelBuilder.Entity("ERPiData.Models.Magacin.Kalkulacija", b =>
                {
                    b.Navigation("Stavke");
                });

            modelBuilder.Entity("ERPiData.Models.Magacin.MaloprodajnaKalkulacija", b =>
                {
                    b.Navigation("Stavke");
                });

            modelBuilder.Entity("ERPiData.Models.Magacin.NivelacijaCena", b =>
                {
                    b.Navigation("Stavke");
                });

            modelBuilder.Entity("ERPiData.Models.Magacin.PrimopredajaNalog", b =>
                {
                    b.Navigation("Stavke");
                });

            modelBuilder.Entity("ERPiData.Models.Magacin.TrebovanjeNalog", b =>
                {
                    b.Navigation("Stavke");
                });

            modelBuilder.Entity("ERPiData.Models.Magacin.UlazNalog", b =>
                {
                    b.Navigation("Stavke");
                });

            modelBuilder.Entity("ERPiData.Models.Magacin.UvoznaKalkulacija", b =>
                {
                    b.Navigation("Stavke");
                });
#pragma warning restore 612, 618
        }
    }
}
