// <auto-generated />
using System;
using ERPiData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ERPiData.Migrations
{
    [DbContext(typeof(ErpiDbContext))]
    partial class ErpiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("ERPiData.Models.Core.Firma", b =>
                {
                    b.Property<int>("FirmaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresa")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FunkcijaZastupnika")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JbkjsBroj")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaticniBroj")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Napomena")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PfrKasirName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PfrPacKod")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PfrSimulatorMod")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PfrUrl")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pib")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("PodracunPoslovneJedinice")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("PosebanRacun")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("PttIMesto")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SefApiKey")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("SefEnvironment")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sifra")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SifraDelatnosti")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("SifraOpstine")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Zastupnik")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("ZiroRacun")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("FirmaId");

                    b.HasIndex("Sifra")
                        .IsUnique();

                    b.ToTable("Firme");
                });

            modelBuilder.Entity("ERPiData.Models.Core.Konto", b =>
                {
                    b.Property<int>("KontoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrojKonta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSintetika")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Klasa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NazivKonta")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("StariKonto")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("VrstaKonta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("KontoId");

                    b.HasIndex("BrojKonta")
                        .IsUnique();

                    b.ToTable("Konta");
                });

            modelBuilder.Entity("ERPiData.Models.Core.Korisnik", b =>
                {
                    b.Property<int>("KorisnikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImeIPrezime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KorisnickoIme")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LozinkaHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PoslednjaPrijava")
                        .HasColumnType("TEXT");

                    b.Property<int>("Uloga")
                        .HasColumnType("INTEGER");

                    b.HasKey("KorisnikId");

                    b.HasIndex("KorisnickoIme")
                        .IsUnique();

                    b.ToTable("Korisnici");

                    b.HasData(
                        new
                        {
                            KorisnikId = 1,
                            ImeIPrezime = "Administrator",
                            IsActive = true,
                            KorisnickoIme = "admin",
                            LozinkaHash = "PBKDF2$100000$CnYWiALqycqWTueq6ayEvQ==$hvm9e8z3e+KVeRsego3azOuoTp3q64deikPgUB9/D4o=",
                            Uloga = 0
                        });
                });

            modelBuilder.Entity("ERPiData.Models.Core.MestoTroska", b =>
                {
                    b.Property<int>("MestoTroskaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAktivno")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Napomena")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sifra")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Tip")
                        .HasColumnType("INTEGER");

                    b.HasKey("MestoTroskaId");

                    b.HasIndex("Sifra")
                        .IsUnique();

                    b.ToTable("MestaTroska");
                });

            modelBuilder.Entity("ERPiData.Models.Core.Partner", b =>
                {
                    b.Property<int>("PartnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresa")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("BankovniRacun")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("JeBanka")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("JeDobavljac")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("JeKupac")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("JePoreskaUprava")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("JeRadnik")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Jmbg")
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("KontoPartnera")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaticniBroj")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NazivBanke")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pib")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("PttIMesto")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SifraPartnera")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ZiroRacun")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("PartnerId");

                    b.HasIndex("SifraPartnera")
                        .IsUnique();

                    b.ToTable("Partneri");
                });
#pragma warning restore 612, 618
        }
    }
}
