<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ERPiData\ERPiData.csproj" />
    <ProjectReference Include="..\..\ERPiFinansije\ERPiFinansijeData\ERPiFinansijeData.csproj" />
    <ProjectReference Include="..\..\ERPiZarade\ERPiZaradeData\ERPiZaradeData.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DbfDataReader" Version="2.2.0" />
    <PackageReference Include="System.Text.Encoding.CodePages" Version="10.0.10" />
  </ItemGroup>

</Project>
